site:
  siteUrl: https://windpo.top # required
  author: windpo
  title: windpo's blog
  description: çƒ­çˆ±ç”Ÿæ´»ã€å–œæ¬¢å­¦ä¹ æ–°äº‹ç‰©çš„æ™®é€šåç«¯å¼€å‘çš„åšå®¢
  motto: "survive and be better"
  indexPageSize: 10 # é¦–é¡µå±•ç¤ºæ–‡ç« æ•°é‡
  pageSize: 10 # åšå®¢æ–‡ç« åˆ†é¡µå¤§å°
  archivePageSize: 25 # å½’æ¡£åˆ†é¡µå¤§å°
  beian: # å¤‡æ¡ˆå·
category:
  - name: "é¦–é¡µ"
    iconClass: "ri-home-4-line"
    href: "/"
    activeName: "home"
  - name: "åšå®¢"
    iconClass: "ri-draft-line"
    href: "/blog/1"
    activeName: "blog"
  - name: "åŠ¨æ€"
    iconClass: "ri-lightbulb-flash-line"
    href: "/activity/1"
    activeName: "activity"
  - name: "å½’æ¡£"
    iconClass: "ri-archive-line"
    href: "/archive/1"
    activeName: "archive"
  - name: "å…³äº"
    iconClass: "ri-user-3-line"
    href: "/about"
    activeName: "about"
  # - name: "ç•™è¨€"
  #   iconClass: "ri-chat-1-line"
  #   href: "/message"
  #   activeName: "message"
  - name: "æœç´¢"
    iconClass: "ri-search-line"
    href: "/search"
    activeName: "search"
info:
  outlinks:
    # - icon: ri-twitter-fill
    #   name: twitter
    #   outlink: https:www.twitter.com/windpo98
    - icon: ri-mail-fill
      name: email
      outlink: mailto:windpo98@gmail.com
    - icon: ri-github-fill
      name: github
      outlink: https:www.github.com/windpo
    - icon: ri-rss-fill
      name: rss
      outlink: /rss.xml
donate:
  enable: false
  tip: "æ„Ÿè°¢å¤§ä½¬é€æ¥çš„å’–å•¡â˜•"
  wechatQRCode:
  alipayQRCode:
  paypalUrl:

comment:
  enable: false # æ˜¯å¦å¼€å¯è¯„è®ºåŠŸèƒ½
  serverUrl: # Waline çš„æœåŠ¡ç«¯åœ°å€
  pageSize: 20 ## The desired number of comments shown in each page.
  wordLimit: ## Limit input word count, 0 means no limit
  requiredMeta: ["nick", "mail"] ## required user information e.g. ['nick','mail','link']
  count: 5 ## The number of recent comments,default. 10
  pageview: false ## æµé‡ç»Ÿè®¡
  reaction: false ## æ˜¯å¦å¼€å¯æ–‡ç« ååº”
ad:
  enable: false
  adItems:
    - link:
      pic:
friends:
  - name: Yumo
    description: è™šå®ä¹‹è°œã€ç”Ÿæ­»è½®å›ã€å®‡å®™å¥¥ç§˜ã€æ¢¦ä¸­æ®‹å¿µã€å¤§é“æ„Ÿæ‚Ÿ
    url: https://yumoyumo.top
    avatar: https://avatars.githubusercontent.com/u/69838566?s=100&v=4

  - name: Xunop
    description: Keep It Simple & Stupid 
    url: https://blog.fooo.in
    avatar: https://avatars.githubusercontent.com/u/97818953?v=4

  - name: Ming
    description: ä¸çŸ¥åå¤§ç –è½¯ä»¶å·¥ç¨‹åœ¨è¯»å­¦ç”Ÿ
    url: https://blog.minng.cc
    avatar: https://avatars.githubusercontent.com/u/87180157?s=100&v=4
  
  - name: NuoTian
    description: è¯ºå¤©çš„å°ä¸–ç•Œ
    url: https://nuotian.furry.pro
    avatar: https://code.furcode.cn/images/avatar_nuotian.jpg

  - name: fengye404
    description:  å‘æ¥å¿ƒæ˜¯çœ‹å®¢å¿ƒï¼Œå¥ˆä½•äººæ˜¯å‰§ä¸­äºº
    url: https://fengye404.top/
    avatar: https://avatars.githubusercontent.com/u/74217701?s=100&v=4 

  - name: love98
    description: Some Simple Techs
    url: https://love98.net/
    avatar: https://avatars.githubusercontent.com/u/77888749?s=100&v=4
  
  - name: LiFeng
    description: è¿˜æœ‰å¥½å¤šè¦å­¦ğŸ˜ª
    url: https://lifeng.dev/page/archives/
    avatar: https://avatars.githubusercontent.com/u/96908064?v=4
  
  - name: Aiden2014
    description: Keep on keeping on 
    url: https://1a4.top/
    avatar: https://avatars.githubusercontent.com/u/54656326?v=4
